### ISSUE TITLE
Q2 2023 is here

### ISSUE THREAD

**Issue by ghost** [julienfdev/sim800#1]
Hey Julien, 

I am working on a similar project (https://github.com/ramtej/sim800-rs), but I want to save my energy and let you go first, :-) 
Joking aside - do you plan to continue with the project? Maybe we can divide the work on it between us. 

Cheers, 
Jiri

**Comment by julienfdev** [comment]
Hey ramtej,

I put the rust version on hold for now, refocusing on a proper TypeScript version because of a business deadline.
crate is yours if you want it, just give me your crate username.

Cheers,
Closing this issue as the next commit is not a Rust one

**Comment by ghost** [comment]
Thanks for the info. In that case, I will also schedule it for later as well. 

Thx!
